config/routes.rb
Rails.application.routes.draw do

  root 'reports#index'

  get 'private_messages/index'
  get 'user_sessions/new'
  get 'user_sessions/destroy'
  get 'reports/search'
  get 'reports/serve'
  get 'emails/new'
  post 'messages/sendMail'
  get 'messages/new'
  post 'emails/sendMail'
  get 'reports/newest'
  get 'reports/search'
  get 'reports/show'

  resources :users
  resources :user_sessions
  resources :private_messages
  resources :reports
  resources :uploads

end

app/models/private_message.rb
class PrivateMessage < ActiveRecord::Base
  belongs_to :user
  belongs_to :report
end

app/controllers/private_messages_controller.rb
class PrivateMessagesController < ApplicationController
  before_action :set_private_message, only: [:show, :edit, :update, :destroy]

  # GET /private_messages
  # GET /private_messages.json
  def index
    @private_messages = PrivateMessage.all
  end

  # GET /private_messages/1
  # GET /private_messages/1.json
  def show
  end

  # GET /private_messages/new
  def new
    @private_message = PrivateMessage.new
  end

  # GET /private_messages/1/edit
  def edit
  end

  # POST /private_messages
  # POST /private_messages.json
  def create
    @private_message = PrivateMessage.new(private_message_params)

    #respond_to do |format|
      if @private_message.save
        redirect_to reports_url + "/" + private_message_params[:report_id]
        #format.html { redirect_to @private_message, notice: 'Private message was successfully created.' }
        #format.json { render :show, status: :created, location: @private_message }
      #else
        #format.html { render :new }
        #format.json { render json: @private_message.errors, status: :unprocessable_entity }
      end
    #end
  end

  # PATCH/PUT /private_messages/1
  # PATCH/PUT /private_messages/1.json
  def update
    respond_to do |format|
      if @private_message.update(private_message_params)
        format.html { redirect_to @private_message, notice: 'Private message was successfully updated.' }
        format.json { render :show, status: :ok, location: @private_message }
      else
        format.html { render :edit }
        format.json { render json: @private_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /private_messages/1
  # DELETE /private_messages/1.json
  def destroy
    @private_message.destroy
    respond_to do |format|
      format.html { redirect_to private_messages_url, notice: 'Private message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_private_message
      @private_message = PrivateMessage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def private_message_params
      params.require(:private_message).permit(:content, :user_id, :report_id)
    end
end

app/helpers/private_messages_helper.rb
module PrivateMessagesHelper
end

app/views/private_messages/_form.html.erb
<%= form_for(@private_message) do |f| %>
  <% if @private_message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@private_message.errors.count, "error") %> prohibited this private_message from being saved:</h2>

      <ul>
      <% @private_message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id, :value => session[:user_id] %>
  </div>
  <div class="field">
    <%= f.label :report_id %>
    <%= f.text_field :report_id, :value => params[:report_id] %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/private_messages/edit.html.erb
<h1>Editing private_message</h1>

<%= render 'form' %>

<%= link_to 'Show', @private_message %> |
<%= link_to 'Back', private_messages_path %>

app/views/private_messages/index.html.erb
<h1>Listing private_messages</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th>Report</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @private_messages.each do |private_message| %>
      <tr>
        <td><%= private_message.content %></td>
        <td><%= private_message.user_id %></td>
        <td><%= private_message.report_id %></td>
        <td><%= link_to 'Show', private_message %></td>
        <td><%= link_to 'Edit', edit_private_message_path(private_message) %></td>
        <td><%= link_to 'Destroy', private_message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Private message', new_private_message_path %>

app/views/private_messages/new.html.erb
<h1>New private_message</h1>

<%= render 'form' %>

<%= link_to 'Back', private_messages_path %>

app/views/private_messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @private_message.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @private_message.user_id %>
</p>

<p>
  <strong>Report:</strong>
  <%= @private_message.report_id %>
</p>

<%= link_to 'Edit', edit_private_message_path(@private_message) %> |
<%= link_to 'Back', private_messages_path %>