config/routes.rb
Rails.application.routes.draw do

  root 'reports#index'

  get 'private_messages/index'
  get 'user_sessions/new'
  get 'user_sessions/destroy'
  get 'reports/search'
  get 'reports/serve'
  get 'emails/new'
  post 'messages/sendMail'
  get 'messages/new'
  post 'emails/sendMail'
  get 'reports/newest'
  get 'reports/search'
  get 'reports/show'

  resources :users
  resources :user_sessions
  resources :private_messages
  resources :reports
  resources :uploads

end

app/models/report.rb
class Report < ActiveRecord::Base
  has_many :private_messages
  belongs_to :user
  attr_accessor :upload


  def self.search(search, user_id)
    if search
      if search == ''
        return
      else
        where("reportname like '%s'", "%#{search}%")
      end
    else
      if user_id
        where("user_id = '%i'", user_id)
      end
    end
  end

  def self.upload(upload)
    path = nil
    if  !upload.nil?
      file_name = upload.original_filename
      file = upload.read
      file_type = file_name.split('.').last
      if file_type == "pdf"
        new_name_file = Time.now.to_i
        name_folder = new_name_file
        new_file_name_with_type = "#{new_name_file}." + file_type

        #image_root = Rails.root + 'app/assets/reports/'
        image_root = "public/uploads/"
        #path = image_root + "#{name_folder}/" + new_file_name_with_type
        path = image_root + "/" + new_file_name_with_type

        #Dir.mkdir(image_root + "#{name_folder}");
        #Dir.mkdir(image_root);
        File.open(path, "wb")  do |f|
          f.write(file)
        end
      else
        path = "invalid"
      end
    end

    return path
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :require_user
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.search(params[:search], session[:user_id])
    #@reports = Report.where("user_id = '%i'", session[:user_id])
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    @private_messages = PrivateMessage.where("report_id = '%i'", params[:id])
    @private_message = PrivateMessage.new
  end

  # GET /reports/new
  def new
    @report = Report.new
    @upload = Upload.new
  end

  def newest
    @newests = Report.where("strftime('%m', 'now')- strftime('%m', created_at)   < 2")
  end

  def search
    @reports = Report.search(params[:search], nil)
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new
    @report.user_id = session[:user_id]
    #@report.reportname = params[:upload]['report_name']
    @report.reportname = report_params[:reportname]

    #save file upload
    path = Report.upload(report_params[:path])
    if !path.nil?
      if path == "invalid"
        flash[:notice] = "Pdf is invalid"
        redirect_to(:back)
        return
      else
        @report.path = path.to_s
      end
    end

    if @report.save
      redirect_to root_url
    end
    #if !path.nil?
      #@report.path = path.to_s

      #respond_to do |format|
      #if @report.save
        #render :text => "File has been uploaded successfully"
        #redirect_to root_url
        #format.html { redirect_to @report, notice: 'Report was successfully created.' }
        #format.json { render :show, status: :created, location: @report }
        #else
        #format.html { render :new }
        #format.json { render json: @report.errors, status: :unprocessable_entity }
      #end
      #end
    #else
      #render :text => "Pdf is invalid"
    #end


  end

  def uploadFile
    post = Report.save(params[:upload])
    render :text => "File has been uploaded successfully"
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    @report.reportname = report_params[:reportname]
    path = Report.upload(report_params[:path])
    if !path.nil?
      if path == "invalid"
        flash[:notice] = "Pdf is invalid"
        redirect_to(:back)
        return
      else
        @report.path = path.to_s
      end
    end

      if @report.save
        redirect_to reports_url + "/" + @report.id.to_s
      end

    #respond_to do |format|
      #if @report.update(report_params)
        #format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        #format.json { render :show, status: :ok, location: @report }
      #else
        #format.html { render :edit }
        #format.json { render json: @report.errors, status: :unprocessable_entity }
      #end
    #end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url }
      format.json { head :no_content }
    end
  end

  def serve
    path = params[:path]
    send_file( path,
               :disposition => 'inline',
               :type => 'application/pdf',
               :x_sendfile => true )
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:reportname, :path, :user_id)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= form_for(@report, html: { multipart: true, class: "dropzone"}) do |f| %>
  <div class="container" style="background-color: #f7f7f9; margin-bottom: 20px">
    <div class="field">
    <%= f.label :reportname %>
    <%= f.text_area :reportname %>
  </div>
  <div class="field">
    <%= f.label "Path (only pdf format)" %>
    <%= f.file_field(:path, accept: 'image/png,image/gif,image/jpeg') %>
    <%= file_field_tag :path,  :accept => 'text/csv' %>
  </div></br>
  </div>
  <div class="actions" style="margin-left: 0px">
    <%= f.submit "Save report", :class => "btn btn-default"%>
  </div>
    <span class="label label-danger"><%= flash[:notice] %></span>
<% end %>

app/views/reports/_form_mail.erb
<h4>New message</h4>

<%= form_tag(:action => 'sendMail', :controller => 'emails') do  %>
    <div class="form-group"><label for="email_subject">Subject</label>
      <%= text_field_tag :subject, :class => "form-control" %></div>>
    <p><label for="email_message">Message</label>
      <%= text_area_tag  :message %></p>
    <p><%= hidden_field_tag :mail_to, params[:user_id] %></p>
    <p><%= hidden_field_tag :report_id, params[:report_id] %></p>
    <p style="margin-left: 150px"><%= submit_tag "Send mail", :class => "btn btn-default" %></p>
<% end %>

<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  <h3 id="myModalLabel">Modal header</h3>
</div>
<div class="modal-body">
  **here comes whatever you want to show!**
</div>
<div class="modal-footer">
  <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
  <button class="btn btn-primary">Save changes</button>
</div>

app/views/reports/edit.html.erb
<div class = "btn btn-default" style="float: right;"><%= link_to 'Back', 'javascript:history.go(-1);' %></div>

<h3 style="color: #337AB7">Editing report</h3>
<%= render 'form' %>

app/views/reports/index.html.erb
<div class = "btn btn-default" style="float: right;"><%= link_to 'New Report', new_report_path %></div>
<h3 style="color: #337AB7">My reports</h3>

<table class="table table-hover">
  <thead>
    <tr>
      <th style="text-align: left"><small>Reportname</small></th>
      <th colspan="1"></th>
    </tr>
  </thead>
  <tbody>
  <% if !@reports.nil? %>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.reportname %></td>
        <td class="button"><a class="fancybox" data-fancybox-type="iframe" href='reports/serve?path=<%= report.path %>'>Review</a></td>
        <td class="button"><%= link_to 'Show', reports_show_path(:id => report.id, :index => "index") %></td>
        <% if report.user_id == session[:user_id] %>
        <td class="button"><%= link_to 'Edit', edit_report_path(report) %></td>
        <td class="button"><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
      </tr>
    <% end %>
      <% end %>
  </tbody>
</table>

app/views/reports/new.html.erb
<div class = "btn btn-default" style="float: right;"><%= link_to 'Back', reports_path %></div>

<h4>New report</h4>

<%= render 'form' %>

app/views/reports/newest.html.erb
<h3 style="color: #337AB7">Newest reports</h3>

<table class="table table-hover">
  <thead>
  <tr>
    <th style="text-align: left"><small>Reportname</small></th>
    <th colspan="1"></th>
  </tr>
  </thead>
  <tbody>

  <% if !@newests.nil? %>
      <% @newests.each do |report| %>
          <tr>
            <td><%= report.reportname %></td>
            <td class="button"><a class="fancybox" data-fancybox-type="iframe" href='serve?path=<%= report.path %>'>Review</a></td>
            <td class="button"><%= link_to 'Show', reports_show_path(:id => report.id, :index => "newest") %></td>
            <% if report.user_id == session[:user_id] %>
                <td class="button"><%= link_to 'Edit', edit_report_path(report) %></td>
                <td class="button"><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
          </tr>
      <% end %>
  <% end %>

  </tbody>
</table>

app/views/reports/search.html.erb
<h3 style="color: #337AB7">Search Reports</h3>

<%= form_tag @report, :method => 'get' do %>
    <p>
      <%= text_field_tag :search %>
      <%= submit_tag "Search", :class => "btn btn-default" %>
    </p>
<% end %>

<% if !@reports.nil? %>
<table class="table table-hover">
  <thead>
  <tr>
    <th style="text-align: left"><h4><small>Report Name</small></h4></th>
    <th style="text-align: left"><h4><small>Post by</small></h4></th>
    <th colspan="1"></th>
  </tr>
  </thead>
  <tbody>
      <% @reports.each do |report| %>
          <tr>
            <td><%= report.reportname %></td>
            <td><%= User.find(report.user_id).username %></td>
            <td class="button"><a class="fancybox" data-fancybox-type="iframe" href='serve?path=<%= report.path %>'>Review</a></td>
            <td class="button"><%= link_to 'Show', reports_show_path(:id => report.id, :index => "search", :search => params[:search]) %></td>
            <% if report.user_id == session[:user_id] %>
                <td class="button"><%= link_to 'Edit', edit_report_path(report) %></td>
                <td class="button"><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
          </tr>
      <% end %>
  </tbody>
</table>
<% end %>

app/views/reports/show.html.erb
<h4 style="color: #337AB7">Report Details</h4>
<div style=" margin-top: 15px; margin-bottom: 15px; border-radius: 5px; font-size: 20px">
<p>
  <small>Report Name:</small>
  <%= @report.reportname %>
</p>
<p>
  <small>Post by:</small>
  <%= User.find(@report.user_id).username %>
</p>
<p class="button"><a class="fancybox" data-fancybox-type="iframe" href='serve?path=<%= @report.path %>'>Review</a></p>
<p class="button"><%= link_to 'Send mail', emails_new_path(:user_id => @report.user_id, :report_id => @report.id),
                              {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window'}  %></p>
<!--
<p class="button"><%= link_to 'Send mail', emails_new_path(:user_id => @report.user_id, :report_id => @report.id) %></p>
-->
  <% if @report.user_id == session[:user_id] %>
<p class="button"><%= link_to 'Edit', edit_report_path(@report) %></p>
  <p class="button"><%= link_to 'Destroy', @report, method: :delete, data: { confirm: 'Are you sure?' } %></p>
      <% end %>
  <p class="button"><%= link_to 'Back', 'javascript:history.go(-1);' %></p>
</div>
<div>
  </br>
  </br>
  <strong>Post comment</strong>
<%= form_for (@private_message) do |f| %>
    <div class="field">
      <%= f.text_area :content %>
    </div>
    <div class="field">
      <%= f.hidden_field :report_id, :value => @report.id %>
    </div>
    <div class="field">
      <%= f.hidden_field :user_id, :value => session[:user_id] %>
    </div>
    <div class="actions">
      <%= submit_tag "Submit", :class => "btn btn-default" %>
    </div>
<% end %>
<strong>Recent Comments</strong>
<% if !@private_messages.nil? %>
    <% @private_messages.each do |pm| %>
          <div class="comment">
        <p>
          <%= pm.content %>
        </p>
        <p>Post by
          <strong><em><%= User.find(pm.user_id).username %></em></strong>
        </p>
          </div>
    <% end %>
<% end %>
</div>

<div id="modal-window" class="modal hide fade in" role="dialog"
     aria-hidden="true" style="display: none; ">

  <div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  <h4>New message</h4>
  <%= form_tag(:action => 'sendMail', :controller => 'emails') do  %>
      <p><label for="email_subject">Subject</label>
        <%= text_field_tag :subject %></p>
      <p><label for="email_message">Message</label>
        <%= text_area_tag  :message %></p>
      <p><%= hidden_field_tag :mail_to, @report.user_id %></p>
      <p><%= hidden_field_tag :report_id, @report.id %></p>
      <p style="margin-left: 150px"><%= submit_tag "Send mail", :class => "btn btn-default" %></p>
  <% end %>
  </div>
</div>